<?php

namespace Database\Factories;

use App\Models\Document;
use App\Models\Workspace;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Document>
 */
class DocumentFactory extends Factory
{
    /**
     * The name of the model being generated by this factory.
     *
     * @var class-string<\App\Models\Document>
     */
    protected $model = Document::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'workspace_id' => Workspace::factory(),
            'user_id' => User::factory(),
            'title' => $this->faker->sentence(5),
            'content' => '<p>' . $this->faker->paragraphs(3, true) . '</p>',
            'order' => 0,
        ];
    }
}
